### ISSUE TITLE
Prettier 3.0 support

### ISSUE THREAD

**Issue by MarcelRoozekrans** [mapado/prettier-plugin-gherkin#8]
Hi, I recently updated prettier but its seems this plugin is not compatibly with the new prettier 3.0 api. 

```
["ERROR" - 9:14:27 AM] printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
    at printEmbeddedLanguages (file:///.../node_modules/prettier/index.mjs:17619:11)
    at printAstToDoc (file:///.../node_modules/prettier/index.mjs:17750:9)
    at async coreFormat (file:///.../node_modules/prettier/index.mjs:18061:14)
    at async formatWithCursor (file:///.../node_modules/prettier/index.mjs:18259:14)
    at async Module.format2 (file:///.../node_modules/prettier/index.mjs:21449:25)

Do you see any chance to update the plugin ?

**Comment by jdeniau** [comment]
Hi !

Thanks for the report 😃 

I see that prettier 3 was out some days ago and that it did break the plugins system. I will look at it today to see if it's an easy upgrade 👍

**Comment by MarcelRoozekrans** [comment]
> Hi !
> 
> Thanks for the report 😃
> 
> I see that prettier 3 was out some days ago and that it did break the plugins system. I will look at it today to see if it's an easy upgrade 👍

Thnx for the quick response ! At a glance it does not look that big :)

**Comment by jdeniau** [comment]
@MarcelRoozekrans the plugin is upgraded for prettier 3 and tested on our main project.

See https://github.com/mapado/prettier-plugin-gherkin/blob/main/CHANGELOG.md#200---2023-08-31 for upgrade guide 👍
